
title: "Sumit's Research Blog"
email: "sumitrwk90@gmail.com"
description: "A log of my daily AI research progress and experiments."
url: "https://sumitrwk90.github.io"
baseurl: "/research-blog" # change if it's a personal site

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM

permalink: /:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

paginate: 5
paginate_path: /page:num/

# Optional settings
author:
  name: "Sumit Kumar"
  avatar: "/assets/images/avatar.png"
  bio: "LLM Researcher | MLOps Developer | Building AutoFlow AI"

# Social links (optional)
social:
  links:
    - https://github.com/your-username
    - https://twitter.com/your-handle

collections:
  posts:
    output: true
